camaar/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
  get "/formularios", to: "formularios#index"
  root to: "home#index"
  devise_for :users
  scope "/turmas" do
    get "/", to: "turmas#index"
    get "/:id", to: "turmas#show"
    # post "/", to: "turmas#create"
    # patch "/:id", to: "turmas#update"
    # delete "/:id", to: "turmas#destroy"
  end
  scope "/matriculas" do
    post "/", to: "matriculas#create"
    delete "/:id", to: "matriculas#delete"
    get "/", to: "matriculas#index"
    # get "/:id", to: "matriculas#show"
    # patch "/:id", to: "matriculas#update"
  end
  scope "/formularios" do
    get "/new", to: "formularios#new"
    get "/", to: "formularios#index"
    get "/:id", to: "formularios#show"
    post "/", to: "formularios#create"
    patch "/:id", to: "formularios#update"
    delete "/:id", to: "formularios#delete"
  end
  scope "/questoes" do
    get "/", to: "questoes#index"
    get "/:id", to: "questoes#show"
    post "/", to: "questoes#create"
    patch "/:id", to: "questoes#update"
    delete "/:id", to: "questoes#delete"
  end
  scope "/respostas" do
    get "/", to: "respostas#index"
    get "/:id", to: "respostas#show"
    post "/", to: "respostas#create"
    patch "/:id", to: "respostas#update"
    delete "/:id", to: "respostas#delete"
  end
  scope "/users" do
    get "/", to: "users#index"
    get "/:id", to: "users#show"
    post "/", to: "users#create"
    patch "/:id", to: "users#update"
    delete "/:id", to: "users#delete"
  end

  resources :materias
  resources :templates
  resources :formularios do
    collection do
      get :export_csv
    end
  end
end

camaar/app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

end

camaar/app/models/department.rb
class Department < ApplicationRecord
  validates :initials, uniqueness: true
end

camaar/app/models/dicente.rb
class Dicente < ApplicationRecord
  has_and_belongs_to_many :turmas, join_table: 'turmas_dicentes'

  validates :matricula, presence: true
  validates :curso, presence: true
end
# este modelo é temporário e irá sofrer alterações no futuro para se adequar às especificações do trabalho

camaar/app/models/docente.rb
class Docente < ApplicationRecord
  has_many :formularios, class_name: 'Formulario'
  has_many :templates, class_name: 'Template'
  has_many :turmas, class_name: 'Turma'
  belongs_to :user

  validates :departamento, presence: true

end
# este modelo é temporário e irá sofrer alterações no futuro para se adequar às especificações do trabalho

camaar/app/models/form.rb
class Form < ApplicationRecord
  # belongs_to :template, optional: true
  belongs_to :coordinator
  belongs_to :subject_class
  has_many :form_question, dependent: :delete_all
end

camaar/app/models/materia.rb
class Materia < ApplicationRecord
  validates :nome, presence: true
  validates :codigo, presence: true, format: { with: /\A[A-Z]{3}[0-9]{4}\z/ }

  has_many :turmas
end

camaar/app/models/matricula.rb
class Matricula < ApplicationRecord
  belongs_to :user
  belongs_to :turma
end

camaar/app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

camaar/app/models/questao.rb
class Questao < ApplicationRecord
  validates :texto, presence: true

  belongs_to :formulario
  belongs_to :template
  has_one :resposta
end

camaar/app/models/question.rb
class Question < ApplicationRecord
  belongs_to :survey
  has_many :options, dependent: :destroy
  accepts_nested_attributes_for :options
end

camaar/app/models/resposta.rb
class Resposta < ApplicationRecord
  belongs_to :questao
  belongs_to :formulario
end

camaar/app/models/respsotas.rb
# app/models/resposta.rb
class Resposta < ApplicationRecord
  belongs_to :resultado
  belongs_to :questao

  validates :conteudo, presence: true
end

camaar/app/models/resultado.rb
class Resultado < ApplicationRecord
  belongs_to :dicente
  belongs_to :formulario

  has_many :respostas, dependent: :destroy, class_name: "Resposta"
  accepts_nested_attributes_for :respostas

  validate :todas_as_questoes_respondidas

  private

  def todas_as_questoes_respondidas
    todas_questoes = formulario.questaos.pluck(:id)
    questoes_respondidas = respostas.map(&:questao_id)

    unless todas_questoes.sort == questoes_respondidas.sort
      errors.add(:base, "Responda a todas as questões do formulário.")
    end
  end
end

camaar/app/models/student.rb
class Student < ApplicationRecord
  validates :email, uniqueness: true
  validates :registration, uniqueness: true
  has_many :enrollment
  has_many :subject_class, :through => :enrollment
  belongs_to :user, optional: true
end

camaar/app/models/survey.rb
class Survey < ApplicationRecord
  has_many :questions, dependent: :destroy
  accepts_nested_attributes_for :questions
end

camaar/app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :department
  belongs_to :user, optional: true
end

camaar/app/models/template.rb
class Template < ApplicationRecord
  validates :nome, presence: true

  has_many :formularios
  has_many :questaos
end

camaar/app/models/tipo.rb
class Tipo < ApplicationRecord
  validates :nome, presence: true
  validates :numeroDeAlternativas, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  validates :discursiva?, presence: true
end

camaar/app/models/turma.rb
class Turma < ApplicationRecord
  validates :codigo, presence: true, format: { with: /\A[A-Z]{2}\z/ }
  validates :semestre, presence: true, format: { with: /\A[0-9]{4}\.[1-2]\z/ }
  validates :horario, presence: true, format: { with: /\A[0-9]{2}[T|N|M][0-9]{2}\z/ }

  belongs_to :materia
  has_one :formulario
  has_many :matriculas
  has_many :users, through: :matriculas
end

camaar/app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable

  validates :nome, presence: true
  validates :email, presence: true
  validates :curso, presence: true
  validates :matricula, presence: true
  validates :formacao, presence: true
  validates :ocupacao, presence: true
  validates :password, presence: true
  # validates :password_confirmation, presence: true


  has_many :matriculas
  has_many :turmas, through: :matriculas

  # Add the role attribute (replace with your desired role types)
  enum role: [:admin, :user]  # This defines roles as 'admin' or 'user'
  after_initialize :set_default_role, :if => :new_record?
  def set_default_role
    self.role ||= :user
  end
end

camaar/app/views/admins/create_template.html.erb
            <div class="main-content">
                <div class="section__content section__content--p30">
                    <div class="container-fluid">

    <div class="formbold-form-wrapper">
                          <h1> Nome do Template</h1>

      <form action="http://localhost:3000/layouts/page" method="GET">

        <div class="formbold-mb-5">
          <label for="qusTwo" class="formbold-form-label">
            Questão 1
          </label>
  
          <div class="formbold-radio-flex">
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusOne"
                  id="qusOne"
                />
                0
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
  
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusOne"
                  id="qusOne"
                />
                 1
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
  
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusOne"
                  id="qusOne"
                />
                2
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
  
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusOne"
                  id="qusOne"
                />
                3
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
            <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusOne"
                    id="qusOne"
                  />
                  4
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusOne"
                    id="qusOne"
                  />
                  5
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
          </div>
        </div>
  
        <div>
          <label for="qusThree" class="formbold-form-label">
            Avalie CIC099
          </label>
  
          <div class="formbold-radio-flex">
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusThree"
                  id="qusThree"
                />
                0
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
  
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusThree"
                  id="qusThree"
                />
                1
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
  
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusThree"
                  id="qusThree"
                />
                2
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
  
            <div class="formbold-radio-group">
              <label class="formbold-radio-label">
                <input
                  class="formbold-input-radio"
                  type="radio"
                  name="qusThree"
                  id="qusThree"
                />
                3
                <span class="formbold-radio-checkmark"></span>
              </label>
            </div>
            <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusThree"
                    id="qusThree"
                  />
                  4
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusThree"
                    id="qusThree"
                  />
                  5
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
          </div>
          <div class="formbold-mb-5">
            <label for="qusOne" class="formbold-form-label">
              Selecione seus melhores professores
            </label>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="checkbox"
                    name="qusOne"
                    id="qusOne"
                  />
                   Genaina Nunes Marques
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="checkbox"
                    name="qusOne"
                    id="qusOne"
                  />
                  Marcus Vinicius Lamar
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="checkbox"
                    name="qusOne"
                    id="qusOne"
                  />
                  Vander Ramos Alves
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
              <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="checkbox"
                      name="qusOne"
                      id="qusOne"
                    />
                    Maristela Terto de Holanda
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
                <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="checkbox"
                      name="qusOne"
                      id="qusOne"
                    />
                    Marcelo Ladeira
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
            </div>
          </div>
          <div class="formbold-input-flex">
            <div>
              <label for="reclamation" class="formbold-form-label">
                Alguma reclamação adicional?
              </label>
              <input
                type="text"
                name="reclamation"
                id="reclamation"
                placeholder="Digite..."
                class="formbold-form-input"
              />
            </div>
        </div>
        
        <button class="formbold-btn">Criar</button>
      </form>
    </div>
  </div>
                        
                    </div>
                </div>
            </div>
       

camaar/app/views/admins/envio.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row justify-content-center align-items-center">
        <div class="col-lg-7">
          <%= render "/layouts/flashes" %>

          <%= form_with url: admins_envio_post_path, method: :post, class: "form-horizontal" do |f| %>
            <div class="card">
              <div class="card-header text-center">
                <strong>Opções para Envio</strong>
              </div>
              <div class="card-body card-block">

                <div class="row form-group">
                  <div class="col col-md-3">
                    <%= f.label :teacher_template, "Professores", class: "form-control-label" %>
                  </div>
                  <div class="col-12 col-md-9">
                    <% if @teacher_templates.present? %>
                     <%= f.select :teacher_template, options_from_collection_for_select(@teacher_templates, :id, :name), { prompt: "Selecione um Template" }, class: "form-control" %>              
                    <% else %>
                      <select disabled class="form-control">
                        <option value="" disabled selected>Nenhum template disponível</option>
                      </select>
                    <% end %>
                  </div>
                </div>

                <div class="row form-group">
                  <div class="col col-md-3">
                    <%= f.label :student_template, "Alunos", class: "form-control-label" %>
                  </div>
                  <div class="col-12 col-md-9">
                    <% if @student_templates.present? %>
                      <%= f.select :student_template, options_from_collection_for_select(@student_templates, :id, :name), { prompt: "Selecione um Template" }, class: "form-control" %>
                    <% else %>
                      <select disabled class="form-control">
                        <option value="" disabled selected>Nenhum template disponível</option>
                      </select>
                    <% end %>
                  </div>
                </div>

                <div class="row form-group">
                  <div class="col col-md-3">
                    <label class="form-control-label">Turmas</label>
                  </div>
                  <div class="col-12 col-md-9">
                    <% if @classes.present? %>
                      <% @classes.each do |subject_class| %>
                        <div class="form-check">
                          <%= f.check_box :classes_ids, { multiple: true, class: "form-check-input", id: "#{subject_class.semester}_#{subject_class.subject}_#{subject_class.code}" }, subject_class.id, nil %>
                          <%= f.label "#{subject_class.semester}_#{subject_class.subject}_#{subject_class.code}", "#{subject_class.semester} - #{subject_class.name} - #{subject_class.code}", class: "form-check-label" %>
                        </div>
                      <% end %>
                    <% else %>
                      <p>Nenhuma turma disponível</p>
                    <% end %>
                  </div>
                </div>

              </div>
              <div class="card-footer justify-content-center align-items-center text-center">
                <%= link_to templates_path, class: "btn btn-danger btn-sm" do %>
                  <i class="fa fa-ban"></i> Cancelar
                <% end %>
                <button type="submit" class="btn btn-success btn-sm" name="commit" value="confirm">
                  <i class="fa fa-dot-circle-o"></i> Enviar
                </button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

camaar/app/views/admins/form_student.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">

      <div class="formbold-form-wrapper">
                            <h1> Avaliação Institucional</h1>

        <form action="http://localhost:3000/layouts/page" method="GET">

          <div class="formbold-mb-5">
            <label for="qusTwo" class="formbold-form-label">
              Avalie CIC0197
            </label>
    
            <div class="formbold-radio-flex">
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusOne"
                    id="qusOne"
                  />
                  0
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusOne"
                    id="qusOne"
                  />
                  1
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusOne"
                    id="qusOne"
                  />
                  2
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusOne"
                    id="qusOne"
                  />
                  3
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
              <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="radio"
                      name="qusOne"
                      id="qusOne"
                    />
                    4
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
                <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="radio"
                      name="qusOne"
                      id="qusOne"
                    />
                    5
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
            </div>
          </div>
    
          <div>
            <label for="qusThree" class="formbold-form-label">
              Avalie CIC099
            </label>
    
            <div class="formbold-radio-flex">
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusThree"
                    id="qusThree"
                  />
                  0
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusThree"
                    id="qusThree"
                  />
                  1
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusThree"
                    id="qusThree"
                  />
                  2
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
    
              <div class="formbold-radio-group">
                <label class="formbold-radio-label">
                  <input
                    class="formbold-input-radio"
                    type="radio"
                    name="qusThree"
                    id="qusThree"
                  />
                  3
                  <span class="formbold-radio-checkmark"></span>
                </label>
              </div>
              <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="radio"
                      name="qusThree"
                      id="qusThree"
                    />
                    4
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
                <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="radio"
                      name="qusThree"
                      id="qusThree"
                    />
                    5
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
            </div>
            <div class="formbold-mb-5">
              <label for="qusOne" class="formbold-form-label">
                Selecione seus melhores professores
              </label>
      
                <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="checkbox"
                      name="qusOne"
                      id="qusOne"
                    />
                    Genaina Nunes Marques
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
      
                <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="checkbox"
                      name="qusOne"
                      id="qusOne"
                    />
                    Marcus Vinicius Lamar
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
      
                <div class="formbold-radio-group">
                  <label class="formbold-radio-label">
                    <input
                      class="formbold-input-radio"
                      type="checkbox"
                      name="qusOne"
                      id="qusOne"
                    />
                    Vander Ramos Alves
                    <span class="formbold-radio-checkmark"></span>
                  </label>
                </div>
                <div class="formbold-radio-group">
                    <label class="formbold-radio-label">
                      <input
                        class="formbold-input-radio"
                        type="checkbox"
                        name="qusOne"
                        id="qusOne"
                      />
                      Maristela Terto de Holanda
                      <span class="formbold-radio-checkmark"></span>
                    </label>
                  </div>
                  <div class="formbold-radio-group">
                    <label class="formbold-radio-label">
                      <input
                        class="formbold-input-radio"
                        type="checkbox"
                        name="qusOne"
                        id="qusOne"
                      />
                      Marcelo Ladeira
                      <span class="formbold-radio-checkmark"></span>
                    </label>
                  </div>
              </div>
            </div>
            <div class="formbold-input-flex">
              <div>
                <label for="reclamation" class="formbold-form-label">
                  Alguma reclamação adicional?
                </label>
                <input
                  type="text"
                  name="reclamation"
                  id="reclamation"
                  placeholder="Digite..."
                  class="formbold-form-input"
                />
              </div>
          </div>
          
          <button class="formbold-btn">Enviar</button>
        </form>
    </div>
  </div>
                       
                    </div>
                </div>
            </div>
            <!-- END MAIN CONTENT-->
       

camaar/app/views/admins/importdata.html.erb
<div class="main-content">
  <div class="section__content section__content--p30">
    <div class="container-fluid">
      <div class="row justify-content-center align-items-center">
        <div class="col-lg-7">
          <% if flash %>
            <% flash.each do |k,v| %>
              <p class="alert alert-success">
                <%= v %>
              </p>
            <% end %>
          <% end %>
          <div class="card">
            <div class="card-header text-center">
              <strong >Opções para Importação</strong>
            </div>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
              <%= simple_form_for :admin_import, url: admins_import_path, method: :post, html: { multipart: true } do |form| %>
                <div class="card-body card-block">
                  <div class="row form-group">
                    <div class="col col-md-3">
                      <label for="select" class="form-control-label">Tipos de Dados</label>
                    </div>
                    <div class="col-12 col-md-9">
                      <%= form.select :select_data, [['Membros', '1'], ['Turmas', '2'], ['Departamentos', '3']], {}, { class: 'form-control', name:"select_data" } %>
                    </div>
                  </div>
                  <div class="row form-group">
                    <div class="col col-md-3">
                      <%= form.label :file, "Arquivo" %>
                    </div>
                    <div class="col-12 col-md-9">
                      <%= form.file_field :file, class: "form-control-file"%> 
                    </div>
                  </div>
                </div>
                <div class="card-footer justify-content-center align-items-center text-center">
                  <%= form.submit "Importar", class: "btn btn-primary btn-sm text-white" %>
                </div>
              <% end %>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>