config/routes.rb
Rails.application.routes.draw do

  devise_for :professors, controllers: {
    sessions: 'professors/sessions'
  }
  devise_for :alunos, controllers: {
    sessions: 'alunos/sessions'
  }

  get 'home/index'


  authenticated :aluno do
    root 'alunos#dashboard', as: :authenticated_aluno_root
  end

  authenticated :professor do
    root 'professors#dashboard', as: :authenticated_professor_root
  end

  root "home#index"



  get 'get_response_files', to: 'formularios#get_response_files'
  get 'list_json_files', to: 'formularios#list_json_files'

  get 'count_responses', to: 'formularios#count_responses'


  post 'submit_form', to: 'reports_alunos#submit_form'

  resources :formularios do
    collection do
      post :save_formulario
    end
  end

  get 'reports_alunos/formularios', to: 'reports_alunos#formularios'
  get 'fetch_form', to: 'reports_alunos#fetch_form'

  get 'view_file_form', to: 'formularios#view_file_form'
  delete 'delete_file_form', to: 'formularios#delete_file_form'
  # Adicione a rota para criação de novos formulários se necessário
  get 'new_formulario', to: 'formularios#new'
  get 'formularios', to: 'formularios#index'

  resources :formularios
  post 'save_formulario', to: 'formularios#save_formulario'

  post 'save_template', to: 'templates#save_template'

  get 'formulario_templates/index'
  get 'formulario_templates/edit_template', to: 'formulario_templates#edit_template', as: 'edit_template'


  delete 'delete_file', to: 'formulario_templates#delete_file'
  get 'view_file', to: 'formulario_templates#view_file'

  get 'templates/check_name', to: 'templates#check_name'

  post 'materia/search_in_sigaa'
  post 'materia/update_with_sigaa_data'

  resources :reports_professors
  resources :reports_alunos
  resources :formulario_templates do
    get 'edit', on: :member
  end
  resources :formularios
  resources :departamentos
  resources :materia
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/formulario_template.rb
class FormularioTemplate < ApplicationRecord
    has_many :formularios
end

app/controllers/formulario_templates_controller.rb
class FormularioTemplatesController < ApplicationController
  before_action :set_formulario_template, only: %i[ show edit update destroy ]

  # GET /formulario_templates or /formulario_templates.json
  def index
    @formulario_templates = FormularioTemplate.all
  end

  # GET /formulario_templates/1 or /formulario_templates/1.json
  def show
  end

  # GET /formulario_templates/new
  def new
    @formulario_template = FormularioTemplate.new
  end

  def set_no_cache
    response.headers["Cache-Control"] = "no-store, no-cache, must-revalidate, max-age=0"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

  # GET /formulario_templates/1/edit
  def edit
  end

  # GET /formulario_templates/edit_no_params
  def edit_template
    templates_dir = Rails.root.join('public', 'templates')
    @files = Dir.children(templates_dir).select { |file| file.end_with?('.json') }

    @formulario_template = FormularioTemplate.first # ou outro critério
    render :edit
  end

  # GET /view_file
  def view_file
    file_name = params[:file_name]
    file_path = Rails.root.join('public', 'templates', file_name)

    if File.exist?(file_path)
      content = File.read(file_path)
      render json: { status: 'success', content: content }
    else
      render json: { status: 'error', message: 'File not found' }, status: 404
    end
  end

  def delete_file
    file_name = params[:file_name]
    file_path = Rails.root.join('public', 'templates', file_name)
    
    if File.exist?(file_path)
      File.delete(file_path)
      render json: { status: 'success', message: 'File deleted successfully' }
    else
      render json: { status: 'error', message: 'File not found' }
    end
  end

  # POST /formulario_templates or /formulario_templates.json
  def create
    @formulario_template = FormularioTemplate.new(formulario_template_params)

    respond_to do |format|
      if @formulario_template.save
        format.html { redirect_to formulario_template_url(@formulario_template), notice: "Formulario template was successfully created." }
        format.json { render :show, status: :created, location: @formulario_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @formulario_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /formulario_templates/1 or /formulario_templates/1.json
  def update
    respond_to do |format|
      if @formulario_template.update(formulario_template_params)
        format.html { redirect_to formulario_template_url(@formulario_template), notice: "Formulario template was successfully updated." }
        format.json { render :show, status: :ok, location: @formulario_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @formulario_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /formulario_templates/1 or /formulario_templates/1.json
  def destroy
    @formulario_template.destroy

    respond_to do |format|
      format.html { redirect_to formulario_templates_url, notice: "Formulario template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formulario_template
      @formulario_template = FormularioTemplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def formulario_template_params
      params.require(:formulario_template).permit(:name, :content)
    end
end

app/helpers/formulario_templates_helper.rb
module FormularioTemplatesHelper
end

app/views/formulario_templates/_form.html.erb
<%= form_with(model: formulario_template) do |form| %>
  <% if formulario_template.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(formulario_template.errors.count, "error") %> prohibited this formulario_template from being saved:</h2>

      <ul>
        <% formulario_template.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :forms_id, style: "display: block" %>
    <%= form.number_field :forms_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/formulario_templates/_formulario_template.html.erb
<div id="<%= dom_id formulario_template %>">
  <p>
    <strong>Forms:</strong>
    <%= formulario_template.forms_id %>
  </p>

</div>

app/views/formulario_templates/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSON Templates</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            display: flex;
            background-color: #f0f0f0;
        }
        .content {
            padding: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
            width: 100%;
        }
        h1 {
            margin-bottom: 20px;
        }
        #search-bar {
            margin-bottom: 20px;
            width: 100%;
            max-width: 500px;
        }
        #search-input {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 2px solid purple;
            border-radius: 5px;
        }
        #buttons-container {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 20px;
            width: 100%;
            max-width: 1400px;
        }
        .button {
            padding: 20px;
            background-color: white;
            color: black;
            border: none;
            border-radius: 10px;
            cursor: pointer;
            display: flex;
            align-items: center;
            justify-content: center;
            text-align: center;
            font-size: 20px;
            border: 3px solid purple;
            transition: 0.5s;
        }
        .button:hover {
            background-color: purple;
            transform: scale(1.1);
        }
        /* Modal styles */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 1; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: auto; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
            padding-top: 60px;
        }
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 80%; /* Could be more or less, depending on screen size */
            max-width: 500px;
            text-align: center;
        }
        .close {
            color: #aaa;
            float: right;
            font-size: 28px;
            font-weight: bold;
        }
        .close:hover,
        .close:focus {
            color: black;
            text-decoration: none;
            cursor: pointer;
        }
        .modal-button {
            padding: 10px 20px;
            margin: 10px;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }
        .view-button {
            background-color: #4CAF50;
            color: white;
            transition: 0.25s;
        }
        .view-button:hover {
            background-color: purple;
            transform: scale(1.05);
            border-radius: 20px;
        }
        .delete-button {
            background-color: #f44336;
            color: white;
            transition: 0.25s;
        }
        .delete-button:hover {
            background-color: darkred;
            transform: scale(1.05);
            border-radius: 20px;
        }
        .template-name {
            font-size: 24px;
            font-weight: bold;
            margin-bottom: 20px;
            text-align: center;
        }
        .button-create-template {
            margin: auto;
            background-color: purple;
            color: white;
            border-radius: 50%;
            cursor: pointer;
            font-size: 30px;
            margin-bottom: 20px;
            width: 50px; /* Define a largura e a altura inicial do botão */
            height: 50px; /* Define a largura e a altura inicial do botão */
            display: flex;
            justify-content: center;
            align-items: center;
            transition: 0.5s;
            border: none; /* Remove qualquer borda padrão */
        }
        .button-create-template:hover {
            background-color: gray;
            transform: scale(1.3);
            border-radius: 10px;
        }


        
        /* Navbar styles */
        .sidebar {
            height: 100%;
            width: 200px;
            position: fixed;
            z-index: 2;
            top: 0;
            left: 0;
            background-color: white;
            overflow-x: hidden;
            padding-top: 20px;
            display: none; /* Initially hidden */
            flex-direction: column;
            align-items: center;
        }
        .sidebar a {
            width: 80%;
            padding: 15px;
            text-decoration: none;
            font-size: 20px;
            color: white;
            display: block;
            text-align: center;
            background-color: purple;
            border-radius: 25px;
            transition: 0.5s;
        }
        .sidebar a:hover {
            background-color: darkviolet;
            border-radius: 10px;
            transform: scale(1.1);
            transform: translateY(-10px);
            
        }
        /* Overlay styles */
        .overlay {
            display: none; /* Initially hidden */
            position: fixed;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: rgba(0, 0, 0, 0.5);
            z-index: 1;
        }
        /* Hamburger button styles */
        .hamburger {
            position: fixed;
            top: 20px;
            left: 20px;
            z-index: 3;
            width: 30px;
            height: 20px;
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            cursor: pointer;
        }

        .hamburger div {
            width: 100%;
            height: 4px;
            background-color: black;
        }
        .hamburger:hover div {
            width: 100%;
            height: 4px;
            background-color: purple;
        }
    </style>
</head>
<body>
    <div class="hamburger" onclick="toggleNavbar()">
        <div></div>
        <div></div>
        <div></div>
    </div>

    <div class="overlay" onclick="toggleNavbar()"></div>

    <div class="sidebar">
        <br><br><br>
        <a id="force-reload-linkF" href="<%= formularios_path %>">Formulários</a>
        <br>
        <a id="force-reload-linkT" href="<%= edit_template_path %>">Templates</a>
        <br>
        <a href="<%= departamentos_path %>">Departamentos</a>
        <script> document.getElementById("force-reload-linkF").addEventListener("click", function(event) { event.preventDefault(); window.location.href = this.href + "?timestamp=" + new Date().getTime(); }); </script>
        <script> document.getElementById("force-reload-linkT").addEventListener("click", function(event) { event.preventDefault(); window.location.href = this.href + "?timestamp=" + new Date().getTime(); }); </script>
    </div>

    <div class="content">
        <br><br>
        <h1>Templates</h1>
        <div id="search-bar">
            <input type="text" id="search-input" onkeyup="searchTemplates()" placeholder="Pesquisar templates...">
        </div>
        <div id="buttons-container">
            <% @files.each do |file| %>
                <button class="button" onclick="handleButtonClick('<%= file %>')" data-name="<%= file %>"><%= file.split('.json')[0] %></button>
            <% end %>

            <%= link_to "+", new_formulario_template_path, id: "force-reload-link", class: "button-create-template" %>
            <script>
                document.getElementById("force-reload-link").addEventListener("click", function(event) {
                    event.preventDefault();
                    window.location.href = this.href + "?timestamp=" + new Date().getTime();
                });
            </script>
        </div>
    </div>

    <!-- The Modal for actions -->
    <div id="fileModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeModal()">&times;</span>
            <p id="modalText"></p>
            <button class="modal-button view-button" onclick="viewFile()">Visualizar</button>
            <button class="modal-button delete-button" onclick="deleteFile()">Deletar</button>
        </div>
    </div>

    <!-- The Modal for viewing content -->
    <div id="viewModal" class="modal">
        <div class="modal-content">
            <span class="close" onclick="closeViewModal()">&times;</span>
            <div class="template-name" id="templateName"></div>
            <div id="fileContent" style="white-space: pre-wrap; text-align: left;"></div>
        </div>
    </div>
    
    <script>
        let selectedFile = '';
        let fileNoExtension = '';

        function handleButtonClick(file) {
            selectedFile = file;
            fileNoExtension = file.split('.json')[0];
            document.getElementById('modalText').innerText = `Template ${fileNoExtension}`;
            document.getElementById('fileModal').style.display = "block";
        }

        function closeModal() {
            document.getElementById('fileModal').style.display = "none";
        }

        function closeViewModal() {
            document.getElementById('viewModal').style.display = "none";
        }

        function viewFile() {
            fetch(`/view_file?file_name=${selectedFile}`)
            .then(response => response.json())
            .then(data => {
                if (data.status === 'success') {
                    const content = JSON.parse(data.content);
                    const templateName = content.templateName;
                    const questions = content.questions;

                    document.getElementById('templateName').innerText = templateName;
                    
                    let formattedContent = '';
                    questions.forEach((question, index) => {
                        const questionType = question.type;
                        if (questionType === 'text') {
                            formattedContent += `Questão ${index + 1} (${questionType})<br>`;
                        } else {
                            const optionsCount = question.options ? question.options.length : 0;
                            formattedContent += `Questão ${index + 1} (${questionType}, ${optionsCount} opções)<br>`;
                        }
                    });

                    document.getElementById('fileContent').innerHTML = formattedContent;
                    closeModal();
                    document.getElementById('viewModal').style.display = "block";
                } else {
                    alert(data.message);
                }
            })
            .catch(error => console.error('Error:', error));
        }

        function deleteFile() {
            if (confirm('Are you sure you want to delete this file?')) {
                fetch(`/delete_file?file_name=${selectedFile}`, {
                    method: 'DELETE',
                    headers: {
                        'X-CSRF-Token': document.querySelector('meta[name="csrf-token"]').content
                    }
                })
                .then(response => response.json())
                .then(data => {
                    alert(data.message);
                    if (data.status === 'success') {
                        location.reload();
                    }
                })
                .catch(error => console.error('Error:', error));
            }
            closeModal();
        }

        // Close the modal when the user clicks anywhere outside of the modal
        window.onclick = function(event) {
            if (event.target == document.getElementById('fileModal')) {
                closeModal();
            }
            if (event.target == document.getElementById('viewModal')) {
                closeViewModal();
            }
        }

        function searchTemplates() {
            let input, filter, buttons, button, i, txtValue;
            input = document.getElementById('search-input');
            filter = input.value.toUpperCase();
            buttons = document.getElementById("buttons-container").getElementsByClassName('button');
            for (i = 0; i < buttons.length; i++) {
                button = buttons[i];
                txtValue = button.textContent || button.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    buttons[i].style.display = "";
                } else {
                    buttons[i].style.display = "none";
                }
            }
        }

        function toggleNavbar() {
            var sidebar = document.querySelector('.sidebar');
            var overlay = document.querySelector('.overlay');
            if (sidebar.style.display === "none" || sidebar.style.display === "") {
                sidebar.style.display = "flex";
                overlay.style.display = "block";
            } else {
                sidebar.style.display = "none";
                overlay.style.display = "none";
            }
        }
    </script>

</body>
</html>

app/views/formulario_templates/index.html.erb
Templates

app/views/formulario_templates/new.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Criação de Templates de Formulário</title>   
</head>
<body>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            background-image: linear-gradient(to right, rgb(223, 223, 223), rgb(189, 189, 189));
        }
    </style>
    <a href="<%= edit_template_path %>" class="button-back">Voltar</a>
    <div class="form-container" id="form-container">
        <form>
            <legend id="legend-NovoTemplate"><b>Novo Template</b></legend>
            <br><br>
            <fieldset>
                <div class="form-group">
                    <input type="text" id="template-name" placeholder="">
                    <label id="label-TemplateName">Nome do Template</label>
                    <br><br>
                </div>
                <div id="questions-container"></div>
                <br>
                <button id="add-question" class="add-buttonT" type="button">Adicionar Questão</button>
                <br><br>
                <button id="create-template" class="create-button" type="button">Criar</button>
            </fieldset>
        </form>
    </div>
    <script>
        window.addEventListener('load', function() {
            const urlParams = new URLSearchParams(window.location.search);
            if (urlParams.has('reload')) {
                // Força o recarregamento da página sem cache
                window.location.href = window.location.pathname;
            }
        });
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"></script>
    <script>
        let questionCount = 0;

        function initialize() {
            const formContainer = document.getElementById('form-container');
            const createButton = document.getElementById('create-template');
            const addButton = document.getElementById('add-question');

            createButton.addEventListener('mouseover', () => {
                formContainer.classList.add('border-change');
            });

            createButton.addEventListener('mouseout', () => {
                formContainer.classList.remove('border-change');
            });

            document.getElementById('template-name').addEventListener('input', function() {
                if (this.value.length > 0) {
                    this.classList.add('has-text');
                    document.getElementById('label-TemplateName').classList.add('has-text');
                } else {
                    this.classList.remove('has-text');
                    document.getElementById('label-TemplateName').classList.remove('has-text');
                }
            });

            addButton.addEventListener('click', addQuestion);
            createButton.addEventListener('click', createTemplate);
        }

        function addQuestion() {
            questionCount++;

            const questionContainer = document.createElement('div');
            questionContainer.classList.add('form-group');
            questionContainer.setAttribute('id', `question-${questionCount}`);
            questionContainer.innerHTML = `
                <label for="question-${questionCount}">Questão ${questionCount}</label>
                <select id="question-type-${questionCount}" class="question-type" onchange="toggleOptions(${questionCount})">
                    <option value="checkbox">Checkbox</option>
                    <option value="text">Texto</option>
                </select>
                <div id="options-container-${questionCount}" class="options-container">
                    <div class="option-buttons" id="option-buttons-${questionCount}">
                        <button type="button" onclick="changeOptionCount(${questionCount}, -1)">-</button>
                        <span class="option-count" id="option-count-${questionCount}">1</span>
                        <button type="button" onclick="changeOptionCount(${questionCount}, 1)">+</button>
                    </div>
                </div>
                <button type="button" class="remove-button" onclick="removeQuestion(${questionCount})">X</button>
            `;

            document.getElementById('questions-container').appendChild(questionContainer);
        }

        function changeOptionCount(questionNumber, delta) {
            const optionCountSpan = document.getElementById(`option-count-${questionNumber}`);
            let optionCount = parseInt(optionCountSpan.textContent);
            optionCount = Math.max(0, optionCount + delta);

            const type = document.getElementById(`question-type-${questionNumber}`).value;
            if (type === 'checkbox' && optionCount === 0) {
                return;
            }
            
            optionCountSpan.textContent = optionCount;
        }

        function toggleOptions(questionNumber) {
            const type = document.getElementById(`question-type-${questionNumber}`).value;
            const optionButtons = document.getElementById(`option-buttons-${questionNumber}`);

            if (type === 'text') {
                optionButtons.style.display = 'none';
            } else {
                optionButtons.style.display = 'flex';
            }
        }

        function removeQuestion(questionNumber) {
            const questionContainer = document.getElementById(`question-${questionNumber}`);
            questionContainer.remove();
            updateQuestionNumbers();
        }

        function updateQuestionNumbers() {
            const questionsContainer = document.getElementById('questions-container');
            const questionContainers = questionsContainer.children;
            questionCount = questionContainers.length;

            for (let i = 0; i < questionCount; i++) {
                const questionContainer = questionContainers[i];
                const questionNumber = i + 1;
                questionContainer.id = `question-${questionNumber}`;
                questionContainer.querySelector('label').setAttribute('for', `question-${questionNumber}`);
                questionContainer.querySelector('label').textContent = `Questão ${questionNumber}`;
                questionContainer.querySelector('.question-type').setAttribute('id', `question-type-${questionNumber}`);
                questionContainer.querySelector('.question-type').setAttribute('onchange', `toggleOptions(${questionNumber})`);
                questionContainer.querySelector('.options-container').setAttribute('id', `options-container-${questionNumber}`);
                questionContainer.querySelector('.option-buttons').setAttribute('id', `option-buttons-${questionNumber}`);
                questionContainer.querySelector('.option-count').setAttribute('id', `option-count-${questionNumber}`);
                questionContainer.querySelector('.remove-button').setAttribute('onclick', `removeQuestion(${questionNumber})`);
            }
        }

        function createTemplate() {
            const templateName = document.getElementById('template-name').value;
            const questions = [];
            const questionContainers = document.getElementById('questions-container').children;

            if (templateName.trim() === "") {
                alert('O nome do template não pode estar em branco.');
                return;
            }

            if (questionContainers.length === 0) {
                alert('O template deve ter pelo menos uma questão.');
                return;
            }

            for (let container of questionContainers) {
                const questionNumber = container.id.split('-')[1];
                const type = document.getElementById(`question-type-${questionNumber}`).value;
                const optionCount = parseInt(document.getElementById(`option-count-${questionNumber}`).textContent);

                if (type === 'checkbox' && optionCount === 0) {
                    alert(`A questão ${questionNumber} do tipo checkbox deve ter pelo menos uma opção.`);
                    return;
                }

                const options = Array(optionCount).fill(null).map((_, idx) => `Opção ${idx + 1}`);
                questions.push({ type, options });
            }

            const templateData = { templateName, questions };

            fetch('/save_template', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ template: templateData }),
            })
            .then(response => response.text())
            .then(data => {
                alert(data);
                window.location.reload(); // Recarrega a página após a criação do template
            })
            .catch(error => {
                console.error('Erro:', error);
                alert('Erro ao salvar o template');
            });
        }

        // Inicializa quando a página é carregada ou quando é mostrada após navegação
        window.addEventListener('pageshow', (event) => {
            if (event.persisted || performance.getEntriesByType('navigation')[0].type === 'back_forward') {
                // Se a página é mostrada novamente depois de navegar para trás ou para frente
                initialize();
            }
        });

        // Inicializa na primeira carga da página
        window.addEventListener('load', initialize);
    </script>
</body>
</html>

app/views/formulario_templates/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @formulario_template %>

<div>
  <%= link_to "Edit this formulario template", edit_formulario_template_path(@formulario_template) %> |
  <%= link_to "Back to formulario templates", formulario_templates_path %>

  <%= button_to "Destroy this formulario template", @formulario_template, method: :delete %>
</div>